using Engine.Graphics;

namespace Editor;

/// <summary>Writes dedicated project-owned collision meshes generated by editor tooling.</summary>
public static class CollisionAssetGenerator
{
    /// <summary>Chunks and writes collision-only source assets into one project directory.</summary>
    /// <param name="source">Explicit source mesh selected by the user.</param>
    /// <param name="directory">Destination project directory.</param>
    /// <param name="baseName">Filesystem-safe base name.</param>
    /// <param name="chunkSize">Spatial generation cell size.</param>
    /// <returns>Absolute generated source paths in deterministic chunk order.</returns>
    public static string[] GenerateChunkFiles(StaticMeshResource source, string directory,
        string baseName, float chunkSize)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentException.ThrowIfNullOrWhiteSpace(directory);
        ArgumentException.ThrowIfNullOrWhiteSpace(baseName);
        if (baseName.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0)
            throw new ArgumentException("Collision asset base name contains invalid characters.",
                nameof(baseName));
        var fullDirectory = Path.GetFullPath(directory);
        Directory.CreateDirectory(fullDirectory);
        var chunks = CollisionMeshChunker.Chunk(source, chunkSize);
        var paths = new string[chunks.Length];
        for (var index = 0; index < chunks.Length; index++)
        {
            var coordinate = chunks[index].Coordinate;
            var path = Path.Combine(fullDirectory,
                $"{baseName}.{coordinate.X}_{coordinate.Y}_{coordinate.Z}.ncollision");
            using var stream = File.Create(path);
            chunks[index].Mesh.Save(stream);
            paths[index] = path;
        }
        return paths;
    }
}
