[package]
name = "nico-player"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nico-presentation = { path = "../../crates/nico-presentation" }
nico-render = { path = "../../crates/nico-render" }
nico-runtime = { path = "../../crates/nico-runtime" }

[lints]
workspace = true
