<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefineConstants>DEBUG_GRAPHICS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Engine.Core/Engine.Core.csproj" />
  </ItemGroup>

</Project>