using Engine.Core;

namespace Engine.Assets;

/// <summary>Identifies the severity of an asset import diagnostic.</summary>
public enum AssetDiagnosticSeverity
{
    /// <summary>Informational import detail.</summary>
    Information,

    /// <summary>Recoverable import concern.</summary>
    Warning,

    /// <summary>Import failure that prevents artifact publication.</summary>
    Error
}

/// <summary>Describes one structured importer message.</summary>
/// <param name="Severity">Diagnostic severity.</param>
/// <param name="Code">Stable machine-readable diagnostic code.</param>
/// <param name="Message">Human-readable diagnostic message.</param>
public sealed record AssetImportDiagnostic(
    AssetDiagnosticSeverity Severity,
    string Code,
    string Message);

/// <summary>Describes one artifact generated by an importer.</summary>
/// <param name="Key">Stable output key within the source asset.</param>
/// <param name="ContentType">Stable runtime content type.</param>
/// <param name="RelativePath">Artifact path relative to its generation directory.</param>
public sealed record AssetArtifact(string Key, string ContentType, string RelativePath);

/// <summary>Contains the declared outputs of one importer execution.</summary>
/// <param name="Artifacts">Generated artifact descriptions.</param>
/// <param name="Dependencies">Persistent assets required by the generated artifacts.</param>
/// <param name="Diagnostics">Structured importer diagnostics.</param>
public sealed record AssetImportResult(
    IReadOnlyList<AssetArtifact> Artifacts,
    IReadOnlyList<AssetReference> Dependencies,
    IReadOnlyList<AssetImportDiagnostic> Diagnostics);

/// <summary>Provides one importer with controlled source and staging access.</summary>
public sealed class AssetImportContext
{
    /// <summary>Gets the absolute source asset path.</summary>
    public string SourcePath { get; }

    /// <summary>Gets authoritative source metadata.</summary>
    public AssetMetadata Metadata { get; }

    /// <summary>Gets the requested build target identifier.</summary>
    public string Target { get; }

    /// <summary>Gets the cancellation request for this importer execution.</summary>
    public CancellationToken CancellationToken { get; }

    /// <summary>Gets the importer-owned temporary publication directory.</summary>
    internal string StagingDirectory { get; }

    /// <summary>Creates an importer context for one isolated execution.</summary>
    /// <param name="sourcePath">Absolute source asset path.</param>
    /// <param name="metadata">Authoritative source metadata.</param>
    /// <param name="target">Requested build target identifier.</param>
    /// <param name="stagingDirectory">Importer-owned temporary output directory.</param>
    /// <param name="cancellationToken">Cancellation request for importer work.</param>
    internal AssetImportContext(
        string sourcePath,
        AssetMetadata metadata,
        string target,
        string stagingDirectory,
        CancellationToken cancellationToken)
    {
        SourcePath = sourcePath;
        Metadata = metadata;
        Target = target;
        StagingDirectory = stagingDirectory;
        CancellationToken = cancellationToken;
    }

    /// <summary>Opens the source asset for sequential reading.</summary>
    /// <returns>A read-only source stream owned by the caller.</returns>
    public Stream OpenSource()
    {
        return new FileStream(SourcePath, FileMode.Open, FileAccess.Read, FileShare.Read,
            81920, FileOptions.SequentialScan);
    }

    /// <summary>Creates one staged artifact file beneath the importer output directory.</summary>
    /// <param name="relativePath">Slash-normalized artifact-relative path.</param>
    /// <returns>A writable artifact stream owned by the caller.</returns>
    public Stream CreateArtifact(string relativePath)
    {
        var fullPath = ResolveArtifactPath(relativePath);
        var directory = Path.GetDirectoryName(fullPath)
            ?? throw new InvalidOperationException("The artifact path has no parent directory.");
        Directory.CreateDirectory(directory);
        return new FileStream(fullPath, FileMode.CreateNew, FileAccess.Write, FileShare.None);
    }

    /// <summary>Validates and resolves one relative artifact path.</summary>
    /// <param name="relativePath">Importer-provided relative path.</param>
    /// <returns>The absolute path beneath the staging directory.</returns>
    private string ResolveArtifactPath(string relativePath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(relativePath);
        if (Path.IsPathRooted(relativePath))
            throw new ArgumentException("Artifact paths must be relative.", nameof(relativePath));
        var fullPath = Path.GetFullPath(Path.Combine(StagingDirectory,
            relativePath.Replace('/', Path.DirectorySeparatorChar)));
        var relative = Path.GetRelativePath(StagingDirectory, fullPath);
        if (relative == ".." || relative.StartsWith($"..{Path.DirectorySeparatorChar}",
                StringComparison.Ordinal))
        {
            throw new ArgumentException("Artifact paths must remain in the staging directory.",
                nameof(relativePath));
        }
        return fullPath;
    }
}

/// <summary>Transforms one supported source asset into runtime-oriented artifacts.</summary>
public interface IAssetImporter
{
    /// <summary>Gets the stable importer identifier stored in metadata.</summary>
    string Id { get; }

    /// <summary>Gets the importer implementation version used for cache invalidation.</summary>
    int Version { get; }

    /// <summary>Imports one source asset into its isolated staging directory.</summary>
    /// <param name="context">Source, metadata, target, and artifact access.</param>
    /// <returns>Declared artifacts, dependencies, and diagnostics.</returns>
    AssetImportResult Import(AssetImportContext context);
}
