schema_version = 1
zone = "meadow"

[models]
tree = "nature/CommonTree_1.glb"
pine = "nature/Pine_1.glb"
rock = "nature/Rock_Medium_1.glb"
rock2 = "nature/Rock_Medium_2.glb"
bush = "nature/Bush_Common.glb"
grass = "nature/Grass_Common_Short.glb"
flowers = "nature/Flower_3_Group.glb"
flowers2 = "nature/Flower_4_Group.glb"
canopy = "nature/CommonTree_3.glb"
twisted = "nature/TwistedTree_1.glb"
fern = "nature/Fern_1.glb"
mushroom = "nature/Mushroom_Common.glb"
flowerbush = "nature/Bush_Common_Flowers.glb"
