[package]
name = "nico-launch"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
server = ["dep:serde_json", "dep:nico-ops", "dep:nico-runtime"]
client = ["dep:png","dep:serde_json", "dep:nico-ops", "dep:nico-runtime", "dep:nico-winit", "dep:nico-input"]

[dependencies]
png = { version = "0.18", optional = true }
clap.workspace = true
nico-ops = { path = "../nico-ops", features = ["bridge"], optional = true }
nico-runtime = { path = "../nico-runtime", optional = true }
nico-winit = { path = "../nico-winit", optional = true }
nico-input = { path = "../nico-input", optional = true }
tracing-subscriber.workspace = true
tracing.workspace = true
serde_json = { version = "1", optional = true }

[lints]
workspace = true
