//! Editor-owned local play sessions. The bridge never owns or launches processes.
mod process;
use nico_ops::bridge::{EditorConnection, EditorRequest};
use process::OwnedProcess;
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::{
    fs,
    io::{self, Read, Write},
    net::SocketAddr,
    path::{Path, PathBuf},
    process::{Command, Stdio},
    sync::{
        Arc, Mutex,
        atomic::{AtomicBool, Ordering},
        mpsc,
    },
    thread::{self, JoinHandle},
    time::{Duration, Instant},
};

/// Local profile inputs. Secrets are read from files and never published in state.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PlayProfile {
    pub project: PathBuf,
    pub bridge: SocketAddr,
    pub editor_endpoint: SocketAddr,
    pub endpoint_token_file: PathBuf,
    #[serde(default)]
    pub release: bool,
}

impl PlayProfile {
    /// Local defaults shared with the documented bridge setup. The token file is
    /// created by setup, never implicitly trusted or regenerated by the editor.
    pub fn for_project(project: &Path) -> Self {
        let project = project
            .canonicalize()
            .unwrap_or_else(|_| project.to_path_buf());
        let root = workspace(&project).unwrap_or_else(|_| project.clone());
        Self {
            project,
            bridge: "127.0.0.1:47631".parse().unwrap(),
            editor_endpoint: "127.0.0.1:47632".parse().unwrap(),
            endpoint_token_file: root.join("target/editor-rpc.token"),
            release: false,
        }
    }
}

/// Joined engine-owned worker. Drop cleans up only directly spawned children.
pub struct PlaySession {
    sender: Option<mpsc::SyncSender<PlayProfile>>,
    worker: Option<JoinHandle<()>>,
    cancelled: Arc<AtomicBool>,
    state: Arc<Mutex<Value>>,
}
impl PlaySession {
    pub fn new() -> io::Result<Self> {
        let (sender, receiver) = mpsc::sync_channel::<PlayProfile>(1);
        let state = Arc::new(Mutex::new(json!({"phase":"idle","active":false})));
        let cancelled = Arc::new(AtomicBool::new(false));
        let shared = state.clone();
        let cancellation = cancelled.clone();
        let worker = thread::Builder::new()
            .name("nico-play".into())
            .spawn(move || {
                while let Ok(profile) = receiver.recv() {
                    let result = run(&profile, &shared, &cancellation);
                    let mut state = shared.lock().unwrap();
                    state["active"] = json!(false);
                    match result {
                        Ok(()) => state["phase"] = json!("exited"),
                        Err(error) => {
                            state["phase"] = json!(if error.kind() == io::ErrorKind::Interrupted {
                                "exited"
                            } else {
                                "failed"
                            });
                            if error.kind() == io::ErrorKind::Interrupted {
                                state["cancelled"] = json!(true);
                            } else {
                                state["error"] = json!(error.to_string());
                            }
                        }
                    }
                }
            })?;
        Ok(Self {
            sender: Some(sender),
            worker: Some(worker),
            cancelled,
            state,
        })
    }
    pub fn start(&self, profile: PlayProfile) -> io::Result<String> {
        if self.sender.is_none() {
            return Err(io::Error::other("play worker closed"));
        }
        if !profile.bridge.ip().is_loopback() || !profile.editor_endpoint.ip().is_loopback() {
            return Err(io::Error::other(
                "play endpoints must be loopback addresses",
            ));
        }
        let mut state = self.state.lock().unwrap();
        if state["active"] == true {
            return Err(io::Error::other("stop the active play session first"));
        }
        let id = uuid::Uuid::new_v4().to_string();
        let previous = state.clone();
        let mut history = previous["previous_sessions"]
            .as_array()
            .cloned()
            .unwrap_or_default();
        if previous["session_id"].is_string() {
            let mut summary = json!({});
            for field in [
                "session_id",
                "phase",
                "error",
                "content_revision",
                "resources_removed",
                "server_progress_saved",
            ] {
                summary[field] = previous[field].clone();
            }
            for role in ["server", "client"] {
                summary[role] = json!({});
                for field in ["pid", "instance_id", "exit_code", "exited", "forced"] {
                    summary[role][field] = previous[role][field].clone();
                }
            }
            history.push(summary);
            if history.len() > 8 {
                history.remove(0);
            }
        }
        *state = json!({"session_id":id,"phase":"preparing","active":true,"server":null,"client":null,"error":null,"previous_sessions":history});
        self.cancelled.store(false, Ordering::Release);
        if self
            .sender
            .as_ref()
            .ok_or_else(|| io::Error::other("play worker closed"))?
            .try_send(profile)
            .is_err()
        {
            *state = previous;
            return Err(io::Error::other("play worker unavailable"));
        }
        Ok(id)
    }
    /// Acceptance requests cancellation/stop; poll state for actual process exit.
    pub fn stop(&self) {
        let mut state = self.state.lock().unwrap();
        if state["active"] == true {
            self.cancelled.store(true, Ordering::Release);
            state["phase"] = json!("stopping");
        }
    }
    pub fn snapshot(&self) -> Value {
        let mut state = self.state.lock().unwrap().clone();
        for role in ["server", "client"] {
            if let Some(observed) = state[role]["observed_unix_ms"].as_u64() {
                state[role]["observation_age_ms"] = json!(now_ms().saturating_sub(observed));
            }
        }
        state
    }
    pub fn shutdown(&mut self) {
        self.stop();
        self.sender.take();
        if let Some(worker) = self.worker.take() {
            let _ = worker.join();
        }
    }
}
impl Drop for PlaySession {
    fn drop(&mut self) {
        self.shutdown();
    }
}

fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis()
        .min(u64::MAX as u128) as u64
}
fn check(cancelled: &AtomicBool) -> io::Result<()> {
    if cancelled.load(Ordering::Acquire) {
        Err(io::Error::new(
            io::ErrorKind::Interrupted,
            "play session cancelled",
        ))
    } else {
        Ok(())
    }
}
fn phase(state: &Mutex<Value>, name: &str) {
    state.lock().unwrap()["phase"] = json!(name);
}
fn workspace(project: &Path) -> io::Result<PathBuf> {
    project
        .ancestors()
        .find(|path| {
            fs::read_to_string(path.join("Cargo.toml"))
                .is_ok_and(|text| text.contains("[workspace]"))
        })
        .map(Path::to_path_buf)
        .ok_or_else(|| io::Error::other("project is not inside a Cargo workspace"))
}
fn read_token(path: &Path) -> io::Result<String> {
    let mut token = String::new();
    fs::File::open(path)?.take(130).read_to_string(&mut token)?;
    let token = token.trim();
    if token.len() != 64 || !token.bytes().all(|b| b.is_ascii_hexdigit()) {
        return Err(io::Error::other("invalid endpoint token file"));
    }
    Ok(token.into())
}
fn connect(profile: &PlayProfile) -> io::Result<EditorConnection> {
    let token = read_token(&profile.endpoint_token_file).map_err(|error| {
        io::Error::new(error.kind(), format!(
            "Cannot read Play endpoint token {}: {error}. Check the token file in Play profile.",
            profile.endpoint_token_file.display()
        ))
    })?;
    EditorConnection::connect(profile.editor_endpoint, token)
        .map_err(|error| connection_error(profile, error))
}
fn connection_error(profile: &PlayProfile, error: io::Error) -> io::Error {
    let recovery = if error.kind() == io::ErrorKind::ConnectionRefused {
        format!(
            "Start or restart nico-bridge with --editor-listen {} --editor-token-file PATH using the token file in Play profile. A bridge listening only on the game registration endpoint ({}) is insufficient. If Codex manages the bridge, restart its MCP connection after updating its launch arguments, then retry Play.",
            profile.editor_endpoint, profile.bridge
        )
    } else {
        "Check the editor endpoint and matching token file in Play profile.".into()
    };
    io::Error::new(
        error.kind(),
        format!(
            "Cannot connect Play to bridge editor endpoint {}: {error}. {recovery}",
            profile.editor_endpoint
        ),
    )
}
fn request(connection: &mut EditorConnection, request: EditorRequest) -> io::Result<Value> {
    let result = connection.request(&request)?;
    if result.is_error == Some(true) {
        return Err(io::Error::other("play RPC request rejected"));
    }
    result
        .structured_content
        .ok_or_else(|| io::Error::other("play RPC returned no structured result"))
}
fn call(connection: &mut EditorConnection, name: &str) -> io::Result<Value> {
    request(
        connection,
        EditorRequest::Call {
            tool_name: name.into(),
            arguments: Default::default(),
        },
    )
}
fn private_policy(path: &Path) -> io::Result<String> {
    let credential = format!(
        "{}{}",
        uuid::Uuid::new_v4().simple(),
        uuid::Uuid::new_v4().simple()
    );
    let mut options = fs::OpenOptions::new();
    options.write(true).create_new(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        options.mode(0o600);
    }
    let mut file = options.open(path)?;
    file.write_all(serde_json::to_string(&json!({"grants":[{"credential":credential,"permissions":["inspect","capture","stop"]}]}))?.as_bytes())?;
    Ok(credential)
}
fn select_instance<'a>(
    list: &'a Value,
    pid: u32,
    role: &str,
    revision: &str,
) -> io::Result<&'a Value> {
    let instance = list["instances"]
        .as_array()
        .and_then(|entries| {
            entries.iter().find(|entry| {
                entry["pid"].as_u64() == Some(pid as u64)
                    && entry["connected"] == true
                    && entry["role"] == role
            })
        })
        .ok_or_else(|| io::Error::other("owned host has not registered"))?;
    if instance["identity"]["content_revision"] != revision {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "owned host content revision mismatch",
        ));
    }
    Ok(instance)
}

struct Host {
    process: OwnedProcess,
    connection: Option<EditorConnection>,
    role: &'static str,
    readiness_tool: String,
    instance: Option<String>,
}
impl Host {
    fn observe(
        &mut self,
        profile: &PlayProfile,
        credential: &str,
        revision: &str,
    ) -> io::Result<Value> {
        if self.connection.is_none() {
            self.connection = Some(connect(profile)?);
        }
        let result = (|| {
            let connection = self.connection.as_mut().unwrap();
            let list = request(connection, EditorRequest::List)?;
            let instance = select_instance(&list, self.process.id(), self.role, revision)?;
            let id = instance["instance_id"]
                .as_str()
                .ok_or_else(|| io::Error::other("host instance ID missing"))?;
            if self.instance.as_deref() != Some(id) {
                request(
                    connection,
                    EditorRequest::Attach {
                        instance_id: id.into(),
                        api_version: instance["api_version"].as_str().unwrap_or("").into(),
                        credential: credential.into(),
                    },
                )?;
                self.instance = Some(id.into());
            }
            let status = call(connection, "status")?;
            let scene = call(connection, &self.readiness_tool)?;
            Ok(
                json!({"pid":self.process.id(),"instance_id":id,"identity":instance["identity"],"connected":true,"host":status,"scene":scene,"observed_unix_ms":now_ms(),"ready":status["ready"] == true && scene["ready"] == true}),
            )
        })();
        if result.is_err() {
            self.connection = None;
            self.instance = None;
        }
        result
    }
    fn stop(&mut self, state: &Mutex<Value>) -> io::Result<()> {
        let accepted = self
            .connection
            .as_mut()
            .is_some_and(|connection| call(connection, "stop").is_ok());
        let (exit, forced) = self.process.stop(if accepted {
            Duration::from_secs(3)
        } else {
            Duration::ZERO
        })?;
        let mut state = state.lock().unwrap();
        if !state[self.role].is_object() {
            state[self.role] = json!({"pid":self.process.id()});
        }
        state[self.role]["exit_code"] = json!(exit.code());
        state[self.role]["exited"] = json!(true);
        state[self.role]["forced"] = json!(forced);
        state[self.role]["connected"] = json!(false);
        state[self.role]["ready"] = json!(false);
        Ok(())
    }
}

fn client_arguments(
    play: &nico_scene::PlayDefinition,
    server_state: &Value,
) -> io::Result<Vec<String>> {
    let address = play
        .server_address
        .as_ref()
        .map(|pointer| {
            let address: SocketAddr = server_state
                .pointer(pointer)
                .and_then(Value::as_str)
                .ok_or_else(|| io::Error::other("owned server did not publish its address"))?
                .parse()
                .map_err(io::Error::other)?;
            if !address.ip().is_loopback() || address.port() == 0 {
                return Err(io::Error::other(
                    "owned server address must use a bound loopback port",
                ));
            }
            Ok(address.to_string())
        })
        .transpose()?;
    play.client_args
        .iter()
        .map(|arg| {
            if arg == "{server_address}" {
                address
                    .clone()
                    .ok_or_else(|| io::Error::other("server address not configured"))
            } else {
                Ok(arg.clone())
            }
        })
        .collect()
}

fn start_host(
    executable: &Path,
    root: &Path,
    project: &Path,
    session: &Path,
    profile: &PlayProfile,
    role: &'static str,
    launch: (&str, &[String]),
) -> io::Result<Host> {
    let mut command = Command::new(executable);
    command
        .current_dir(root)
        .args([
            "--enable-debug",
            "--bridge",
            &profile.bridge.to_string(),
            "--debug-access-file",
        ])
        .arg(session.join("host-access.json"))
        .arg("--project")
        .arg(project)
        .stdin(Stdio::null());
    if role == "client" {
        command.arg("--background");
    }
    if role == "server" {
        command.arg("--data-dir").arg(session.join("server-data"));
    }
    command.args(launch.1);
    Ok(Host {
        readiness_tool: launch.0.into(),
        process: OwnedProcess::spawn(&mut command)?,
        connection: None,
        role,
        instance: None,
    })
}
fn ready(
    host: &mut Host,
    profile: &PlayProfile,
    credential: &str,
    revision: &str,
    state: &Mutex<Value>,
    cancelled: &AtomicBool,
) -> io::Result<()> {
    // A project's first launch can import character assets not used by the editor.
    // Subsequent launches reuse that project's cache; cold imports still need a
    // bounded startup allowance rather than being killed after thirty seconds.
    let deadline = Instant::now() + Duration::from_secs(120);
    loop {
        check(cancelled)?;
        if let Some(exit) = host.process.poll()? {
            return Err(io::Error::other(format!(
                "{} exited before ready: {exit}",
                host.role
            )));
        }
        let observation = host.observe(profile, credential, revision);
        if let Err(error) = &observation
            && error.kind() == io::ErrorKind::InvalidData
        {
            return Err(io::Error::new(error.kind(), error.to_string()));
        }
        let ready = observation
            .as_ref()
            .is_ok_and(|value| value["ready"] == true);
        state.lock().unwrap()[host.role] = match &observation {
            Ok(value) => value.clone(),
            Err(error) => {
                json!({"pid":host.process.id(),"connected":false,"ready":false,"error":error.to_string()})
            }
        };
        if ready {
            return Ok(());
        }
        if Instant::now() >= deadline {
            return Err(io::Error::other(format!(
                "{} readiness timed out",
                host.role
            )));
        }
        thread::sleep(Duration::from_millis(100));
    }
}
fn run(profile: &PlayProfile, state: &Mutex<Value>, cancelled: &AtomicBool) -> io::Result<()> {
    check(cancelled)?;
    // Verify editor admission before building or launching children.
    let mut admission = connect(profile)?;
    request(&mut admission, EditorRequest::List)?;
    drop(admission);
    let project = nico_scene::Project::open(&profile.project)?;
    let client_target = project
        .manifest
        .targets
        .client
        .as_deref()
        .ok_or_else(|| io::Error::other("profile requires a client target"))?;
    let server_target = project
        .manifest
        .targets
        .server
        .as_deref()
        .ok_or_else(|| io::Error::other("profile requires a server target"))?;
    let root = workspace(project.root())?;
    let directory = project.root().join(".nico/play");
    fs::create_dir_all(&directory)?;
    let lock = fs::OpenOptions::new()
        .read(true)
        .write(true)
        .create(true)
        .truncate(false)
        .open(directory.join("session.lock"))?;
    lock.try_lock().map_err(|error| {
        io::Error::other(format!("project Play session is already in use: {error}"))
    })?;
    let policy = directory.join("host-access.json");
    match fs::remove_file(&policy) {
        Ok(()) => {}
        Err(error) if error.kind() == io::ErrorKind::NotFound => {}
        Err(error) => return Err(error),
    }
    let result = (|| {
        // Hosts load the saved project in place, sharing its existing import cache.
        // Reuse one project-local Play directory and the normal Cargo binaries.
        let content_path = project.root();
        let data = directory.join("server-data");
        fs::create_dir_all(&data)?;
        let credential = private_policy(&policy)?;
        {
            let mut state = state.lock().unwrap();
            state["content_path"] = json!(content_path);
            state["session_path"] = json!(directory);
            state["server_data"] = json!(data);
        }
        phase(state, "building");
        let target_dir = root.join("target");
        let mut command = Command::new("cargo");
        command
            .current_dir(&root)
            .args([
                "build",
                "-p",
                client_target,
                "-p",
                server_target,
                "--target-dir",
            ])
            .arg(&target_dir)
            .stdin(Stdio::null());
        if profile.release {
            command.arg("--release");
        }
        let mut build = OwnedProcess::spawn_build(&mut command)?;
        let build_deadline = Instant::now() + Duration::from_secs(600);
        loop {
            if Instant::now() >= build_deadline {
                return Err(io::Error::other("play build exceeded ten minutes"));
            }
            check(cancelled)?;
            if let Some(exit) = build.poll()? {
                if !exit.success() {
                    return Err(io::Error::other(format!("play build failed: {exit}")));
                }
                break;
            }
            thread::sleep(Duration::from_millis(100));
        }
        let bin = target_dir.join(if profile.release { "release" } else { "debug" });
        let executable =
            |target: &str| bin.join(format!("{target}{}", std::env::consts::EXE_SUFFIX));
        // Measure saved content after the build, so edits made while Cargo runs
        // do not invalidate the launch before either host even opens the project.
        let revision =
            nico_scene::content::revision(&project, &|| cancelled.load(Ordering::Acquire))?;
        state.lock().unwrap()["content_revision"] = json!(revision);
        check(cancelled)?;
        phase(state, "starting_server");
        let mut server = start_host(
            &executable(server_target),
            &root,
            content_path,
            &directory,
            profile,
            "server",
            (
                &project.manifest.play.server_tool,
                &project.manifest.play.server_args,
            ),
        )?;
        let mut client: Option<Host> = None;
        let result = (|| {
            ready(
                &mut server,
                profile,
                &credential,
                &revision,
                state,
                cancelled,
            )?;
            let client_arguments = client_arguments(
                &project.manifest.play,
                &state.lock().unwrap()["server"]["scene"],
            )?;
            phase(state, "starting_client");
            client = Some(start_host(
                &executable(client_target),
                &root,
                content_path,
                &directory,
                profile,
                "client",
                (&project.manifest.play.client_tool, &client_arguments),
            )?);
            let client = client.as_mut().unwrap();
            ready(client, profile, &credential, &revision, state, cancelled)?;
            phase(state, "running");
            loop {
                if cancelled.load(Ordering::Acquire) {
                    break;
                }
                for host in [&mut server, &mut *client] {
                    if let Some(exit) = host.process.poll()? {
                        return Err(io::Error::other(format!(
                            "{} exited during play: {exit}",
                            host.role
                        )));
                    }
                    match host.observe(profile, &credential, &revision) {
                        Ok(value) => state.lock().unwrap()[host.role] = value,
                        Err(error) => {
                            let mut state = state.lock().unwrap();
                            state[host.role]["connected"] = json!(false);
                            state[host.role]["ready"] = json!(false);
                            state[host.role]["observation_error"] = json!(error.to_string());
                        }
                    }
                }
                thread::sleep(Duration::from_millis(250));
            }
            Ok(())
        })();
        phase(state, "stopping");
        let client_cleanup = client.as_mut().map(|host| host.stop(state)).transpose();
        let server_cleanup = server.stop(state);
        // Reap children before removing credentials. Project, cache and saves persist.
        drop(client);
        drop(server);
        state.lock().unwrap()["server_progress_saved"] =
            json!(data.join("progress.json").is_file());
        client_cleanup?;
        server_cleanup?;
        result
    })();
    let removed = match fs::remove_file(&policy) {
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(()),
        result => result,
    };
    state.lock().unwrap()["resources_removed"] = json!(removed.is_ok());
    removed?;
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    fn profile() -> PlayProfile {
        PlayProfile {
            project: PathBuf::from("unused"),
            bridge: "127.0.0.1:1".parse().unwrap(),
            editor_endpoint: "127.0.0.1:1".parse().unwrap(),
            endpoint_token_file: PathBuf::from("missing-play-token"),
            release: false,
        }
    }
    #[test]
    fn immediate_shutdown_finalizes_accepted_start_and_closed_workers_reject_new_work() {
        let mut session = PlaySession::new().unwrap();
        let id = session.start(profile()).unwrap();
        session.shutdown();
        let final_state = session.snapshot();
        assert_eq!(final_state["session_id"], id);
        assert_eq!(final_state["active"], false);
        assert!(matches!(
            final_state["phase"].as_str(),
            Some("exited" | "failed")
        ));
        assert!(session.start(profile()).is_err());
        assert_eq!(session.snapshot()["active"], false);
    }
    #[test]
    fn refused_play_connection_identifies_editor_endpoint_and_recovery() {
        let mut profile = profile();
        profile.editor_endpoint = "127.0.0.1:47632".parse().unwrap();
        profile.bridge = "127.0.0.1:47631".parse().unwrap();
        let error = connection_error(&profile, io::ErrorKind::ConnectionRefused.into());
        assert_eq!(error.kind(), io::ErrorKind::ConnectionRefused);
        let message = error.to_string();
        assert!(message.contains("editor endpoint 127.0.0.1:47632"));
        assert!(message.contains("--editor-listen 127.0.0.1:47632"));
        assert!(message.contains("restart its MCP connection"));
        assert!(message.contains("registration endpoint (127.0.0.1:47631)"));
        let denied = connection_error(&profile, io::ErrorKind::PermissionDenied.into());
        assert!(!denied.to_string().contains("--editor-listen"));
    }
    #[test]
    fn missing_credentials_fail_without_launching_hosts_and_nonlocal_profiles_are_rejected() {
        let mut session = PlaySession::new().unwrap();
        let mut nonlocal = profile();
        nonlocal.bridge = "192.0.2.1:47631".parse().unwrap();
        assert!(session.start(nonlocal).is_err());
        session.start(profile()).unwrap();
        let deadline = Instant::now() + Duration::from_secs(2);
        while session.snapshot()["active"] == true && Instant::now() < deadline {
            thread::sleep(Duration::from_millis(5));
        }
        let state = session.snapshot();
        assert_eq!(state["phase"], "failed");
        assert!(state["server"].is_null() && state["client"].is_null());
        session.shutdown();
    }
    #[test]
    fn discovery_requires_the_owned_pid_role_live_connection_and_matching_revision() {
        let mut list = json!({"instances":[
            {"pid":12,"role":"server","connected":true,"identity":{"content_revision":"expected"}},
            {"pid":13,"role":"server","connected":true,"identity":{"content_revision":"wrong"}}
        ]});
        assert_eq!(
            select_instance(&list, 13, "server", "expected")
                .unwrap_err()
                .kind(),
            io::ErrorKind::InvalidData
        );
        list["instances"][1]["identity"]["content_revision"] = Value::Null;
        assert!(select_instance(&list, 13, "server", "expected").is_err());
        list["instances"][1]["identity"]["content_revision"] = json!("expected");
        assert_eq!(
            select_instance(&list, 13, "server", "expected").unwrap()["pid"],
            13
        );
        assert!(select_instance(&list, 13, "client", "expected").is_err());
        list["instances"][1]["connected"] = json!(false);
        assert!(select_instance(&list, 13, "server", "expected").is_err());
    }

    #[test]
    fn client_uses_only_the_owned_servers_published_loopback_endpoint() {
        let play = nico_scene::PlayDefinition {
            client_args: vec!["--server".into(), "{server_address}".into()],
            server_address: Some("/address".into()),
            ..Default::default()
        };
        assert_eq!(
            client_arguments(&play, &json!({"address":"127.0.0.1:52345"})).unwrap(),
            ["--server", "127.0.0.1:52345"]
        );
        for state in [
            json!({}),
            json!({"address":"192.0.2.1:52345"}),
            json!({"address":"127.0.0.1:0"}),
            json!({"address":"$(malformed)"}),
        ] {
            assert!(client_arguments(&play, &state).is_err());
        }
    }

    #[test]
    fn generated_policy_grants_stop_without_mutation_and_stays_private() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("policy.json");
        let credential = private_policy(&path).unwrap();
        assert_eq!(credential.len(), 64);
        let value: Value = serde_json::from_slice(&fs::read(&path).unwrap()).unwrap();
        assert_eq!(
            value["grants"][0]["permissions"],
            json!(["inspect", "capture", "stop"])
        );
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_eq!(
                fs::metadata(path).unwrap().permissions().mode() & 0o777,
                0o600
            );
        }
    }
}
