[package]
name = "nico-winit"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nico-input = { path = "../nico-input" }
nico-ops = { path = "../nico-ops" }
nico-presentation = { path = "../nico-presentation" }
nico-render = { path = "../nico-render" }
nico-rhi = { path = "../nico-rhi" }
nico-rhi-wgpu = { path = "../nico-rhi-wgpu" }
nico-runtime = { path = "../nico-runtime" }
pollster.workspace = true
tracing.workspace = true
winit.workspace = true

[lints]
workspace = true
