[package]
name = "minimal-game-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
minimal-game-shared = { path = "../shared", features = ["tools"] }
nico-launch = { path = "../../../crates/nico-launch", features = ["server"] }
nico-runtime = { path = "../../../crates/nico-runtime" }
tracing.workspace = true

[dev-dependencies]
nico-ops = { path = "../../../crates/nico-ops" }

[lints]
workspace = true
