<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Engine.Core/Engine.Core.csproj" />
    <ProjectReference Include="../Engine.Graphics/Engine.Graphics.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BepuPhysics" Version="2.4.0" />
  </ItemGroup>
</Project>
