[package]
name = "arena-arpg-shared"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
tools = ["dep:nico-ops"]
network = ["dep:nico-net"]

[dependencies]
nico-net = { path = "../../../crates/nico-net", optional = true }
nico-ecs = { path = "../../../crates/nico-ecs" }
nico-assets = { path = "../../../crates/nico-assets", features = ["character"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
nico-physics = { path = "../../../crates/nico-physics", default-features = false }
nico-runtime = { path = "../../../crates/nico-runtime" }
nico-ops = { path = "../../../crates/nico-ops", features = ["mcp"], optional = true }
serde_json = "1"

[lints]
workspace = true
