[package]
name = "minimal-game-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
minimal-game-shared = { path = "../shared" }
nico-input = { path = "../../../crates/nico-input" }
nico-launch = { path = "../../../crates/nico-launch" }
nico-runtime = { path = "../../../crates/nico-runtime" }
nico-winit = { path = "../../../crates/nico-winit" }
tracing.workspace = true

[lints]
workspace = true
