[package]
name = "minimal-game-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nico-assets = { path = "../../../crates/nico-assets", features = ["loading"] }
nico-presentation = { path = "../../../crates/nico-presentation" }
nico-ops = { path = "../../../crates/nico-ops", features = ["mcp"] }
serde_json = "1"
clap.workspace = true
minimal-game-shared = { path = "../shared", features = ["tools"] }
nico-input = { path = "../../../crates/nico-input" }
nico-launch = { path = "../../../crates/nico-launch", features = ["client"] }
nico-runtime = { path = "../../../crates/nico-runtime" }
nico-winit = { path = "../../../crates/nico-winit" }
tracing.workspace = true

[dev-dependencies]
nico-ops = { path = "../../../crates/nico-ops" }

[lints]
workspace = true
