<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Engine.Graphics/Engine.Graphics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HarfBuzzSharp" Version="14.2.1.1" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="14.2.1.1" />
    <PackageReference Include="StbTrueTypeSharp" Version="1.26.12" />
    <PackageReference Include="Silk.NET" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.EXT" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Vulkan" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Maths" Version="2.23.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="../Shaders/basic.vert.spv" LogicalName="basic.vert.spv" />
    <EmbeddedResource Include="../Shaders/basic.frag.spv" LogicalName="basic.frag.spv" />
    <EmbeddedResource Include="../Shaders/texture.vert.spv" LogicalName="texture.vert.spv" />
    <EmbeddedResource Include="../Shaders/texture.frag.spv" LogicalName="texture.frag.spv" />
    <EmbeddedResource Include="../Shaders/grid.vert.spv" LogicalName="grid.vert.spv" />
    <EmbeddedResource Include="../Shaders/grid.frag.spv" LogicalName="grid.frag.spv" />
    <EmbeddedResource Include="../Shaders/model.vert.spv" LogicalName="model.vert.spv" />
    <EmbeddedResource Include="../Shaders/model.frag.spv" LogicalName="model.frag.spv" />
  </ItemGroup>

</Project>
